version: "3.9"
services:
  development:
    build: 
      context: .
      args:
        DEFAULT_USER: ${DEFAULT_USER:?}
        NODE_VERSION: ${NODE_VERSION:-19.4}
    container_name: development
    image: development
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "80:80"
    hostname: "development"
    volumes: 
      - type: bind
        source: ${WORKSPACE:?}
        target: /home/${DEFAULT_USER:?}/workspace
    depends_on:
      - mariadb
    environment:
      PHP_ERROR_REPORTING: E_ALL
      TZ: ${TIME_ZONE:-UTC}
  mariadb:
    image: "mariadb:10"
    ports:
      - "3306:3306"
    hostname: mariadb
    environment:
      TZ: ${TIME_ZONE:-UTC}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
